### ISSUE TITLE
What are the hardware requirements for this?

### ISSUE THREAD

**Issue by BrianHepler** [gfischershaw/MMM-Touch#4]
I'm trying to test some module compatibility and I can't get the touch event to fire. Even a straight default configuration doesn't produce the expected alert.

I don't have a touch screen on my Pi, but viewing it though a web browser on two different computers. One of which has a touch screen. Clicking on the button doesn't fire the event (Chrome, Firefox). Touching on the button (Edge) doesn't fire the event. No messages in the console, no messages on the Pi.

**Comment by eouia** [comment]
No special H/W be required except touch features. Hmmm. Frankly said, it would be activated by mouse (limited 1 finger)

**Comment by BrianHepler** [comment]
The straight default config should give me a button that says "default" and shows an alert if I click on it, correct? Can you give it a quick try and see if you're seeing my problem?

**Comment by BrianHepler** [comment]
Sorry, let me add some more detail. This should be a very basic configuration:
`{
			module: "MMM-Touch",
			position: "bottom_left",
			config: {
				debug: true,
				gestureCommands: {
					"default": {
						"TAP_1": (commander) => {
						  commander.sendNotification("SHOW_ALERT", { title: "TOUCH Test.", timer: 3000 });
						},
					}
				}
			}
		},`

I'm seeing the button and the "default" label, but I'm not seeing the TAP_1 in the button. I should, right?

**Comment by eouia** [comment]
tap once in empty space anywhere. `debug:true` will show some information on your front dev-console.

**Comment by BrianHepler** [comment]
Negative. All I see in the console log is `[TOUCH] New Gesture` on page load. Clicking anywhere doesn't produce any messages.

**Comment by BrianHepler** [comment]
I ended up implementing a button elsewhere. I may revisit this later, but my need for it is gone. Closing as OBE.
