### ISSUE TITLE
[feature request]: send custom notifications on "touchStarted()"

### ISSUE THREAD

**Issue by skuethe** [gfischershaw/MMM-Touch#6]
Hey there,

awesome module you guys have here. Thanks for all your work.
I have a specific request and wanted to share with you if we could implement it here:

I want to be able to send customizable notifications when *ANY* touch is used.
Use-case: I don't have a PIR connected to my Pi, and want to be able to send the monitor into "sleep" mode after nobody used it for some time. Some basics in this module would be usable in that matter, but we are lacking some "send a notification after X amount of time after you clicked something" function. Implementing all of this is in this module is maybe a bit over the top, so I was wondering if we could go a step "smaller" and just be able to send custom notifications when you are actually using the touch functionality.

So to be more clear:
1. Every time I am using some touch gesture, the "touchStarted()" function will trigger my custom notification (f.e. "TOUCH_GESTURE_TRIGGERED", maybe even including the gesture as a payload?)
2. A third party module could pick up this notification and react on it - f.e. some "sleep" module, which is always resetting a timer when receiving the above triggered notification and, if no notification arrives for X time, will put your monitor to sleep

The alternative would be to implement the touch process into the "sleep" module, but that seems waisted time and effort, as everything is here in place :)

Tell me what you think about that. Thanks!

**Comment by eouia** [comment]
I was the original developer but have taken this module to @gfischershaw at this moment, so this is not the official reply from this module owner.

1) The best thing would be to make that feature by yourself then make a PR to share it with others. I believe you would have enough skills to do that considering your post.
https://github.com/gfischershaw/MMM-Touch/blob/4f8322ac3de75efbe7427af511d6563fdc80f33e/MMM-Touch.js#L246-L252
You can insert notification emitter in this function or somewhere.
```js
...
this.sendNotification('TOUCH_GESTURE_TRIGGERED')
...
```
Not tested. 



2) Some of my other `commandable` modules have `onIdle/onWakeup` features, but as I know, nobody uses it well, so I omitted those features in this module. Sorry. 

Anyway, @gfischershaw may have a better opinion. :) I'll dive into deep-sea again.

**Comment by skuethe** [comment]
Thanks for the quick feedback! Yeah I'll have a look at it over the weekend. Just wanted to get your opinion on this and if you are up for PRs / modifications :)

A good dive to you ;)

**Comment by gfischershaw** [comment]
The notification sounds like an excellent idea, I assume this is also an issue if a video is playing and one would like the display to stay active? So a more general activity message rather than touch-specific?

**Comment by skuethe** [comment]
Well I feel that everybody has to define for themselfs what "active" means, right?
I want to define it as **"nobody used the touch screen in a while"**

A lot of ppl use PIR to capture movement, others use webcams or other motion sensors to determine that **"somebody is home, please activate the mirror / screen"** or **"no motion detectred for X minutes, please deactivate mirror / screen"**.

I think implementing this "touch was used" notitifcation can help those people (me :D) which:
- do not have such sensors or a webcam attached
- have a touch enabled display and use your (wide spread) module

But actually reacting on this notification should be in the "hands" of other modules - like one of the many "disable my screen" modules.

So in your "a video is playing" example, I would see it in the hands of the video module to send some "VIDEO_IS_STILL_PLAYING" notification every now and then, so that the third party "turn screen off" module can react on it.

I hope that is making it clear where I was heading with the idea :)

**Comment by gfischershaw** [comment]
Another option might be a generic Activity notification with an activity-specific payload. E.g.,
ACTIVITY_NOTIFICATION, TOUCH_GESTURE_TRIGGERED
ACTIVITY_NOTIFICATION, VIDEO_IS_STILL_PLAYING

Clients would then need to only pay attention to a single notification. For the video notification the current inactivity timeout would need to be known so that the module could send notifications with the correct periodicity. Unless the payload was a VIDEO_STARTED_PLAYING and VIDEO_STOPPED_PLAYING.

Thoughts? Not trying to be difficult. Just not wanting to jump into something without a bit of thought.

**Comment by skuethe** [comment]
> 
> 
> Another option might be a generic Activity notification with an activity-specific payload. E.g.,
> ACTIVITY_NOTIFICATION, TOUCH_GESTURE_TRIGGERED
> ACTIVITY_NOTIFICATION, VIDEO_IS_STILL_PLAYING
> 
> Clients would then need to only pay attention to a single notification. For the video notification the current inactivity timeout would need to be known so that the module could send notifications with the correct periodicity. Unless the payload was a VIDEO_STARTED_PLAYING and VIDEO_STOPPED_PLAYING.
> 
> Thoughts? Not trying to be difficult. Just not wanting to jump into something without a bit of thought.

Okay, I think I get where you are going with this. You want to make it a "generic" notification message (= a specific notification name) which could be shared across different modules and is not tide to this module or its name, right?

My thoughts about this:
- (_pro_) makes it easier to implement stuff on the receiving modules, as you could "hard code" this notification name and do stuff when receiving it
- (_con_) you would still need to differentiate between the different payloads if you want to have special reaction to a special "thing" happening (like you probably want to do different things on a `VIDEO_STARTED_PLAYING` payload than on a `VIDEO_STOPPED_PLAYING`
- (_con_) you would need to share this idea in the community forum to spread the idea around and hope others are using the same name for the notification
- (_con_) you would loose the possibility to pass the touch gesture as a payload if the payload itself is set to `TOUCH_GESTURE_TRIGGERED`, of course you could then send specific payloads like `TOUCH_DOUBLETAB_1_TRIGGERED` (or whatever), but maybe that is making the implementation on this modules side a bit overkill

Please add to the list or correct me if I thought about it in a wrong way.
Currently I feel this would be a bit over the top and could be implemented a lot easier with more or less the same outcome / effort

**Comment by skuethe** [comment]
Sorry I just added a PR for now and set the notification to `TOUCH_ACTIVITY_NOTIFICATION`.
Feel free to adjust :)

Also sending the current gesture as a payload is probably not the best idea, because we then would need to send it after an actual gesture was detected - which somehow goes against an "activity notification" :)

**Comment by eouia** [comment]
This is just an idea.

- You can use custom notification or custom hooking callback by little modification.

1) add some definition in config/default
```js
defaults: {
  ...
  onTouchStart: null, // or text for notification, or function for callback
  onTouchEnd: null, // or text for notification, or function for callback
  ...
```

2) Then you can modify the source to apply it.  
```js
touchStarted: function() { 
  ...
  if (typeof this.config.onTouchStart == 'string') this.sendNotification(this.config.onTouchStart)
  if (typeof this.config.onTouchStart == 'function') this.config.onTouchStart().bind(this)
},
```
(`touchEnded` function needs to be also modified for `onTouchEnd`)

3) Example;
```js
// in user config
onTouchStart: 'MY_CUSTOM_NOTI'
```
will emit `MY_CUSTOM_NOTI'. 
Or,
```js
onTouchStart: () => {
  setTimeout(() => {
    this.sendNotification('MY_DELAYED_NOTI', ...)
  }, 500)
}
```


4) You may expand to implement `onIdle/onWakeup` feature like this;
```js
touchStarted: function() {
  clearTimeout(this.idleTimer)
  this.idleTimer = null
  
  var dom = document.getElementById("TOUCH")
  dom.classList.add("activated")
  var command = document.querySelector("#TOUCH .command")
  command.innerHTML = ""
  command.classList.remove("fired")

  if (typeof this.config.onTouchStart == 'string') this.sendNotification(this.config.onTouchStart)
  if (typeof this.config.onTouchStart == 'function') this.config.onTouchStart().bind(this)
},

touchEnded: function() {
  clearTimeout(this.idleTimer)
  this.idleTimer = null
  
  var dom = document.getElementById("TOUCH")
  dom.classList.remove("activated")

  if (typeof this.config.onTouchEnd == 'string') this.sendNotification(this.config.onTouchEnd)
  if (typeof this.config.onTouchEnd == 'function') this.config.onTouchEnd().bind(this)

  if (this.config.onIdle && this.config.threshold.idle_ms > 0) {
    this.idleTimer = setTimeout(() => {
      if (typeof this.config.onIdle === 'string') this.sendNotification(this.config.onIdle)
      if (typeof this.config.onIdle === 'function') this.config.onIdle().bind(this)
    }, this.config.threshold.idle_ms)
  }
},
```

**Comment by skuethe** [comment]
Sure, that looks also very good. Then you would have complete control. Somehow now need a decision of @gfischershaw what he prefers and which way he wants to go :)

**Comment by gfischershaw** [comment]
I for one very much like eouia's latest idea. If you modify your PR, then I can apply that.

**Comment by skuethe** [comment]
So, I've updated the PR: #7 

Some changes to the idea of @eouia:
- [I set idleTimer module global](https://github.com/gfischershaw/MMM-Touch/pull/7/commits/83dcce162f47c5f08aa9dd44fe5ac42d9f432858#diff-1adcbe1439e57a80b073dd01dbe81ab93806ab07d7a8dd87e73a57cd38f4ab08R65), so that we can [reset it also on touchStarted](https://github.com/gfischershaw/MMM-Touch/pull/7/commits/83dcce162f47c5f08aa9dd44fe5ac42d9f432858#diff-1adcbe1439e57a80b073dd01dbe81ab93806ab07d7a8dd87e73a57cd38f4ab08R252) - if you have a small `config.threshold.idle_ms` (f.e. 5 seconds) and do a long touch gesture (f.e. some MOVE*) for > `config.threshold.idle_ms`, then onIdle would trigger while we are actually still using touch
- calling `this.config.onIdle().bind(this)` (same for `onTouchStart()` and `onTouchEnd()`) would throw an "is undefined" error for `onIdle()` when we define a fuction. I changed it to `this.config.onIdle()` (same of course for the other two). This seems to work as far as I could test, but I am not sure if we can "fall down a pit" with this for some edge case config, as I am doing this JS stuff for a hobby ;)

Tell me what you think.

**Comment by skuethe** [comment]
Thank you for your support on this. It seems that updating the documentation needs to be done by you, right? Or can I somehow do PRs for that?

**Comment by gfischershaw** [comment]
Should be able to just do an edit and I can approve like code.

**Comment by skuethe** [comment]
Unfortunately there is no edit option.
I added the changes to the MD in the feature branch so you can just copy & paste if you want:
https://github.com/skuethe/MMM-Touch/blob/feature/notificationOnTouch/Manual.md

**Comment by gfischershaw** [comment]
Pasted in.
